Django_Test_Task/urls.py
"""
Метод POST должен всегда использоваться,
если отправка данных приведет к внесению изменений в базе данных на сервере.
Применение данного метода должно повысить уровень защиты от CSRF.
Метод GET должен применяться только для форм,
действия с которыми не приводят к изменению базы данных (например для поисковых запросов).
Кроме того, данный метод рекумендуется применять для создания внешних ссылок на ресурсы сайта.
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('index.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('teachers/', include('teachers.urls')),
    path('classes/', include('classes.urls')),
    path('users/', include('users.urls')),
    path('schedules/', include('schedules.urls')),
]

index/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

teachers/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    path('', views.teachers, name='teachers'),
    # path('', views.TeachersListView.as_view(), name='teachers'),
    url(r'ajax/$', views.ajax, name='ajax')
]

teachers/models.py
from django.db import models


class Teacher(models.Model):
    last_name = models.CharField(max_length=20, default='')
    first_name = models.CharField(max_length=20, default='')
    patronymic = models.CharField(max_length=20, default='')
    full_name = models.CharField(max_length=100, default='')

    def __str__(self):
        return "{0} {1} {2}".format(self.last_name, self.first_name, self.patronymic)

    class Meta:
        verbose_name = 'преподаватель'
        verbose_name_plural = 'Преподаватели'
        ordering = ['full_name']

teachers/forms.py
from django import forms

from .models import *


class TeacherForm(forms.Form):
    model = Teacher

    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}),
                                max_length=32)
    first_name = forms.CharField(label='Имя',
                                 widget=forms.TextInput(attrs={'class': 'form-control'}),
                                 max_length=32)
    patronymic = forms.CharField(label='Отчество', widget=forms.TextInput(attrs={'class': 'form-control'}))

teachers/views.py
# from django.shortcuts import render
import json

from django.http import HttpResponse
from django.shortcuts import render

from teachers.forms import TeacherForm
from .models import Teacher


def teachers(request):
    teacher_list = Teacher.objects.all()

    form = TeacherForm(request.POST or None)

    return render(request, 'teachers/teacher_list.html', locals())


def ajax(request):
    if request.method == "GET":
        if 'delete_data' in request.GET:
            response = []
            teacher_id = request.GET['delete_data']

            deleted_user = Teacher.objects.get(id=teacher_id)

            deleted_user.delete()
        else:
            response = []
            teacher_last_name = request.GET['teacher_last_name']
            teacher_first_name = request.GET['teacher_first_name']
            teacher_patronymic = request.GET['teacher_patronymic']
            teacher_full_name = (str(teacher_last_name) + ' ' +
                                 str(teacher_first_name) + ' ' +
                                 str(teacher_patronymic))

            try:
                teacher = Teacher.objects.get(full_name=teacher_full_name)
            except Teacher.DoesNotExist:
                teacher = Teacher()

            teacher.last_name = teacher_last_name
            teacher.first_name = teacher_first_name
            teacher.patronymic = teacher_patronymic
            teacher.full_name = teacher_full_name

            teacher.save()

        teachers_data = Teacher.objects.all()

        for teacher in teachers_data:
            response.append(str(teacher) + ' ' + str(teacher.id))

        return HttpResponse(json.dumps(response, ensure_ascii=False), content_type="application/javascript")
    else:
        return HttpResponse('Error', content_type='text/html')

# class TeachersListView(ListView):
#     model = Teacher
#     paginate_by = 5
#     template_name = 'teachers/teacher_list.html'

templates/teachers/teacher_list.html
{% extends 'base_generic.html' %}
{% block title %}<title>Преподаватели</title>{% endblock %}
{% load static %}
{% block content %}
    <script src="{% static 'js/teacher_ajax.js' %}" type="text/javascript"></script>
    <table class="table table-bordered">
        <thead>
        <tr class="active">
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Кнопка для удаления</th>
        </tr>
        </thead>
        <tbody id="id_teachers">
        {% for teacher in teacher_list %}
            <tr>
                <td>{{ teacher.last_name }} </td>
                <td>{{ teacher.first_name }} </td>
                <td>{{ teacher.patronymic }} </td>
                <td>
                    <button type="button" value="{{ teacher.id }}" class="btn btn-danger deleteTeacherBtn"
                            id="id_delete_teacher">
                        Удалить
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {#    TODO почему-то не видит has_group#}
    {#    {% if request.user|has_group:'Работник деканата' %}#}
    <form method="post" id="teacher_form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_last_name">Фамилия</label>
            {{ form.last_name }}
        </div>
        <div class="form-group">
            <label for="id_first_name">Имя</label>
            {{ form.first_name }}
        </div>
        <div class="form-group">
            <label for="id_patronymic">Отчество</label>
            {{ form.patronymic }}
        </div>
    </form>
    <button type="submit" class="btn btn-primary" id="id_add_teacher">
        Сохранить
    </button>
{% endblock %}