Django_Test_Task/urls.py
"""
Метод POST должен всегда использоваться,
если отправка данных приведет к внесению изменений в базе данных на сервере.
Применение данного метода должно повысить уровень защиты от CSRF.
Метод GET должен применяться только для форм,
действия с которыми не приводят к изменению базы данных (например для поисковых запросов).
Кроме того, данный метод рекумендуется применять для создания внешних ссылок на ресурсы сайта.
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('index.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('teachers/', include('teachers.urls')),
    path('classes/', include('classes.urls')),
    path('users/', include('users.urls')),
    path('schedules/', include('schedules.urls')),
]

classes/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.ClassesListView.as_view(), name='classes'),
    path('', views.classes, name='classes'),
    url(r'ajax/$', views.ajax, name='ajax')
]

index/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

classes/models.py
from django.db import models

from teachers.models import Teacher


class Class(models.Model):
    title = models.CharField(primary_key=True, max_length=30, default='')
    description = models.CharField(max_length=500, default='')
    teacher = models.ForeignKey(Teacher, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{0}".format(self.title)

    class Meta:
        verbose_name = 'предмет'
        verbose_name_plural = 'Предметы'
        ordering = ['title']

classes/forms.py
from django import forms


class ClassForm(forms.Form):
    title = forms.CharField(label='Название', widget=forms.TextInput(attrs={'class': 'form-control'}),
                            max_length=32)
    description = forms.CharField(label='Описание',
                                  widget=forms.TextInput(attrs={'class': 'form-control'}),
                                  max_length=32)

classes/views.py
# from django.shortcuts import render
import json

from django.http import HttpResponse
from django.shortcuts import render

from classes.forms import ClassForm
from teachers.models import Teacher
from .models import Class


def classes(request):
    class_list = Class.objects.all()
    teacher_list = Teacher.objects.all()

    form = ClassForm(request.POST or None)

    return render(request, 'classes/class_list.html', locals())


def ajax(request):
    if request.method == "GET":
        if 'delete_data' in request.GET:
            response = []
            class_title = request.GET['delete_data']

            deleted_class = Class.objects.get(title=class_title)

            deleted_class.delete()
        else:
            response = []
            class_title = request.GET['class_title']
            class_description = request.GET['class_description']
            teacher = Teacher.objects.get(full_name=request.GET['class_teacher'])
            class_teacher = teacher

            try:
                new_class = Class.objects.get(title=class_title)
            except Class.DoesNotExist:
                new_class = Class()

            new_class.title = class_title
            new_class.description = class_description
            new_class.teacher = class_teacher

            new_class.save()

        classes_data = Class.objects.all()

        for _class in classes_data:
            response.append(str(_class.title) + ', ' + str(_class.description) + ', ' + str(_class.teacher))

        return HttpResponse(json.dumps(response, ensure_ascii=False), content_type="application/javascript")
    else:
        return HttpResponse('Error', content_type='text/html')

# class ClassesListView(ListView):
#     model = Class
#     paginate_by = 10
#     template_name = 'classes/class_list.html'

templates/classes/class_list.html
{% extends 'base_generic.html' %}
{% block title %}<title>Предметы</title>{% endblock %}
{% load static %}
{% block content %}
    <script src="{% static 'js/class_ajax.js' %}" type="text/javascript"></script>
    <table class="table table-bordered">
        <thead>
        <tr class="active">
            <th>Название</th>
            <th>Описание</th>
            <th>Преподаватель</th>
            <th>Кнопка для удаления</th>
        </tr>
        </thead>
        <tbody id="id_classes">
        {% for class in class_list %}
            <tr>
                <td>{{ class.title }} </td>
                <td>{{ class.description }} </td>
                <td>{{ class.teacher }} </td>
                <td>
                    <button type="button" value="{{ class.title }}" class="btn btn-danger deleteClassBtn"
                            id="id_delete_class">
                        Удалить
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {#    {% if request.user|has_group:'Работник деканата' %}#}
    <form method="post" id="class_form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Название</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description">Описание</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_teacher">Преподаватель</label>
            <select id="id_teacher" class="form-control" name="teacher">
                <option value="None">---------</option>
                {% for teacher in teacher_list %}
                    <option value="{{ teacher }}">{{ teacher }}</option> %}
                {% endfor %}
            </select>
        </div>
    </form>
    <button type="submit" class="btn btn-primary addClassBtn" id="id_add_class">
        Сохранить
    </button>
{% endblock %}